/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoint2;

import Model.bean.Funcionario;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
public class TelaCadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroFuncionario
     */
    public TelaCadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomefuncionario = new javax.swing.JPanel();
        txtnome = new javax.swing.JTextField();
        txtdatanascimento = new javax.swing.JFormattedTextField();
        txtendereco = new javax.swing.JTextField();
        txtcpf = new javax.swing.JFormattedTextField();
        txtemail = new javax.swing.JTextField();
        rdbfuncao = new javax.swing.JComboBox<>();
        salvar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomefuncionario.setBackground(new java.awt.Color(255, 255, 255));
        nomefuncionario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        nomefuncionario.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 220, 20));

        try {
            txtdatanascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdatanascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatanascimentoActionPerformed(evt);
            }
        });
        nomefuncionario.add(txtdatanascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 220, 20));

        txtendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtenderecoActionPerformed(evt);
            }
        });
        nomefuncionario.add(txtendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 220, 20));

        try {
            txtcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcpfActionPerformed(evt);
            }
        });
        nomefuncionario.add(txtcpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 220, 20));

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        nomefuncionario.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 220, 20));

        rdbfuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha", "Estoquista", "Vendedor", "Barista", "Cozinheiro" }));
        rdbfuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbfuncaoActionPerformed(evt);
            }
        });
        nomefuncionario.add(rdbfuncao, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 220, 20));

        salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAOSALVAR.png"))); // NOI18N
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });
        nomefuncionario.add(salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 100, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/TELA CADASTRO FUNCIONÁRIOS.png"))); // NOI18N
        nomefuncionario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 490));

        getContentPane().add(nomefuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void txtdatanascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatanascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatanascimentoActionPerformed

    private void txtenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtenderecoActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void rdbfuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbfuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbfuncaoActionPerformed

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
     Funcionario f = new Funcionario();
if(txtnome.getText().isEmpty()||txtdatanascimento.getText().isEmpty()||txtcpf.getText().isEmpty()||txtendereco.getText().isEmpty()||txtemail.getText().isEmpty()){
        JOptionPane.showMessageDialog(null,"POR FAVOR, PREENCHA TODOS OS DADOS!");
}        
        f.setNomefuncionario(txtnome.getText());
                   
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        try{
            f.setDatanascimento(format.parse(txtdatanascimento.getText()));
        }catch(ParseException e){
            e.printStackTrace();
        }
        f.setCpf(txtcpf.getText());
        f.setEmail(txtemail.getText());
        f.setEndereco(txtendereco.getText());
 if(rdbfuncao.getSelectedItem().equals("Vendedor")){
           f.setFuncao("Vendedor");
     JOptionPane.showMessageDialog(null,"CADASTRO REALIZADO COM SUCESSO!");
     
       }
       else if(rdbfuncao.getSelectedItem().equals("Estoquista")){
           f.setFuncao("Estoquista");
       JOptionPane.showMessageDialog(null,"CADASTRO REALIZADO COM SUCESSO!");
       }
       else if(rdbfuncao.getSelectedItem().equals("Barista")){
            f.setFuncao("Barista");
       JOptionPane.showMessageDialog(null,"CADASTRO REALIZADO COM SUCESSO!");

       }
       else if(rdbfuncao.getSelectedItem().equals("Cozinheiro")){
            f.setFuncao("Cozinheiro");
       JOptionPane.showMessageDialog(null,"CADASTRO REALIZADO COM SUCESSO!");
       }

    }//GEN-LAST:event_salvarActionPerformed

    private void txtcpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel nomefuncionario;
    private javax.swing.JComboBox<String> rdbfuncao;
    private javax.swing.JButton salvar;
    private javax.swing.JFormattedTextField txtcpf;
    private javax.swing.JFormattedTextField txtdatanascimento;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtendereco;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
