/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoint2;

/**
 *
 * @author gatar
 */
public class TelaMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nome9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSpinner18 = new javax.swing.JSpinner();
        jButton20 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nome1 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jSpinner22 = new javax.swing.JSpinner();
        jPanel19 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nome2 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jSpinner21 = new javax.swing.JSpinner();
        jButton13 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nome3 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jSpinner20 = new javax.swing.JSpinner();
        jButton14 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        nome4 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jSpinner19 = new javax.swing.JSpinner();
        jButton15 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        nome5 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jSpinner23 = new javax.swing.JSpinner();
        jButton19 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jSpinner7 = new javax.swing.JSpinner();
        nome6 = new javax.swing.JLabel();
        jCheckBox7 = new javax.swing.JCheckBox();
        jButton18 = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        nome7 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jSpinner13 = new javax.swing.JSpinner();
        jButton17 = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        nome8 = new javax.swing.JLabel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jSpinner14 = new javax.swing.JSpinner();
        jButton16 = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        nome12 = new javax.swing.JLabel();
        jCheckBox10 = new javax.swing.JCheckBox();
        jSpinner15 = new javax.swing.JSpinner();
        jButton23 = new javax.swing.JButton();
        jPanel27 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        nome11 = new javax.swing.JLabel();
        jCheckBox11 = new javax.swing.JCheckBox();
        jSpinner16 = new javax.swing.JSpinner();
        jButton22 = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        nome10 = new javax.swing.JLabel();
        jCheckBox12 = new javax.swing.JCheckBox();
        jSpinner17 = new javax.swing.JSpinner();
        jButton21 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(840, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel6.setText("NOME:");
        jPanel17.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel8.setText("QUANTIDADE:");
        jPanel17.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel9.setText("VALOR:");
        jPanel17.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel10.setText("ADICIONAR:");
        jPanel17.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel2.setText("jLabel2");
        jPanel17.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel3.setText("jLabel3");
        jPanel17.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome9.setText("jLabel3");
        jPanel17.add(nome9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel17.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        jPanel17.add(jSpinner18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel17.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 160, 200));

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel11.setText("NOME:");
        jPanel18.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel12.setText("QUANTIDADE:");
        jPanel18.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel13.setText("VALOR:");
        jPanel18.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel14.setText("ADICIONAR:");
        jPanel18.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel5.setText("jLabel2");
        jPanel18.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel15.setText("jLabel3");
        jPanel18.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome1.setText("jLabel3");
        jPanel18.add(nome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel18.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel18.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));
        jPanel18.add(jSpinner22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jPanel1.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 160, 200));

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel17.setText("NOME:");
        jPanel19.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel18.setText("QUANTIDADE:");
        jPanel19.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel19.setText("VALOR:");
        jPanel19.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel20.setText("ADICIONAR:");
        jPanel19.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel21.setText("jLabel2");
        jPanel19.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel22.setText("jLabel3");
        jPanel19.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome2.setText("jLabel3");
        jPanel19.add(nome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel19.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        jPanel19.add(jSpinner21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel19.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 160, 200));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel24.setText("NOME:");
        jPanel20.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel25.setText("QUANTIDADE:");
        jPanel20.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel26.setText("VALOR:");
        jPanel20.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel27.setText("ADICIONAR:");
        jPanel20.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel28.setText("jLabel2");
        jPanel20.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel29.setText("jLabel3");
        jPanel20.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome3.setText("jLabel3");
        jPanel20.add(nome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel20.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        jPanel20.add(jSpinner20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel20.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 160, 200));

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel31.setText("NOME:");
        jPanel21.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel32.setText("QUANTIDADE:");
        jPanel21.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel33.setText("VALOR:");
        jPanel21.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel34.setText("ADICIONAR:");
        jPanel21.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel35.setText("jLabel2");
        jPanel21.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel36.setText("jLabel3");
        jPanel21.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome4.setText("jLabel3");
        jPanel21.add(nome4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel21.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        jPanel21.add(jSpinner19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel21.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 160, 200));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel38.setText("NOME:");
        jPanel22.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel39.setText("QUANTIDADE:");
        jPanel22.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel40.setText("VALOR:");
        jPanel22.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel41.setText("ADICIONAR:");
        jPanel22.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel42.setText("jLabel2");
        jPanel22.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel43.setText("jLabel3");
        jPanel22.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome5.setText("jLabel3");
        jPanel22.add(nome5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel22.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        jPanel22.add(jSpinner23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel22.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 160, 200));

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel45.setText("NOME:");
        jPanel23.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel46.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel46.setText("QUANTIDADE:");
        jPanel23.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel47.setText("VALOR:");
        jPanel23.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel48.setText("ADICIONAR:");
        jPanel23.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel49.setText("jLabel2");
        jPanel23.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel50.setText("jLabel3");
        jPanel23.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));
        jPanel23.add(jSpinner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        nome6.setText("jLabel3");
        jPanel23.add(nome6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel23.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel23.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 160, 200));

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel52.setText("NOME:");
        jPanel24.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel53.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel53.setText("QUANTIDADE:");
        jPanel24.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel54.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel54.setText("VALOR:");
        jPanel24.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel55.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel55.setText("ADICIONAR:");
        jPanel24.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel56.setText("jLabel2");
        jPanel24.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel57.setText("jLabel3");
        jPanel24.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome7.setText("jLabel3");
        jPanel24.add(nome7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel24.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        jPanel24.add(jSpinner13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel24.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 160, 200));

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel59.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel59.setText("NOME:");
        jPanel25.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel60.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel60.setText("QUANTIDADE:");
        jPanel25.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel61.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel61.setText("VALOR:");
        jPanel25.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel62.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel62.setText("ADICIONAR:");
        jPanel25.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel63.setText("jLabel2");
        jPanel25.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel64.setText("jLabel3");
        jPanel25.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome8.setText("jLabel3");
        jPanel25.add(nome8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel25.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        jPanel25.add(jSpinner14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel25.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 310, 160, 200));

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel66.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel66.setText("NOME:");
        jPanel26.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel67.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel67.setText("QUANTIDADE:");
        jPanel26.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel68.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel68.setText("VALOR:");
        jPanel26.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel69.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel69.setText("ADICIONAR:");
        jPanel26.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel70.setText("jLabel2");
        jPanel26.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel71.setText("jLabel3");
        jPanel26.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome12.setText("jLabel3");
        jPanel26.add(nome12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanel26.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        jPanel26.add(jSpinner15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel26.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 520, 160, 200));

        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel73.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel73.setText("NOME:");
        jPanel27.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel74.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel74.setText("QUANTIDADE:");
        jPanel27.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel75.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel75.setText("VALOR:");
        jPanel27.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel76.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel76.setText("ADICIONAR:");
        jPanel27.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel77.setText("jLabel2");
        jPanel27.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel78.setText("jLabel3");
        jPanel27.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome11.setText("jLabel3");
        jPanel27.add(nome11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel27.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        jPanel27.add(jSpinner16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel27.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 520, 160, 200));

        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel80.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel80.setText("NOME:");
        jPanel28.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 20));

        jLabel81.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel81.setText("QUANTIDADE:");
        jPanel28.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel82.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel82.setText("VALOR:");
        jPanel28.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        jLabel83.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel83.setText("ADICIONAR:");
        jPanel28.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel84.setText("jLabel2");
        jPanel28.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 60));

        jLabel85.setText("jLabel3");
        jPanel28.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, -1));

        nome10.setText("jLabel3");
        jPanel28.add(nome10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 80, -1));

        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel28.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));
        jPanel28.add(jSpinner17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 50, -1));

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/BOTAO MUDAR.png"))); // NOI18N
        jPanel28.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 60, 20));

        jPanel1.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 520, 160, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetoint2/Imagens/Tela do Menu GRANDE.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 1300, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-190, -20, 1480, 720));

        getAccessibleContext().setAccessibleName("TELA MENU");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner14;
    private javax.swing.JSpinner jSpinner15;
    private javax.swing.JSpinner jSpinner16;
    private javax.swing.JSpinner jSpinner17;
    private javax.swing.JSpinner jSpinner18;
    private javax.swing.JSpinner jSpinner19;
    private javax.swing.JSpinner jSpinner20;
    private javax.swing.JSpinner jSpinner21;
    private javax.swing.JSpinner jSpinner22;
    private javax.swing.JSpinner jSpinner23;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JLabel nome1;
    private javax.swing.JLabel nome10;
    private javax.swing.JLabel nome11;
    private javax.swing.JLabel nome12;
    private javax.swing.JLabel nome2;
    private javax.swing.JLabel nome3;
    private javax.swing.JLabel nome4;
    private javax.swing.JLabel nome5;
    private javax.swing.JLabel nome6;
    private javax.swing.JLabel nome7;
    private javax.swing.JLabel nome8;
    private javax.swing.JLabel nome9;
    // End of variables declaration//GEN-END:variables
}
